### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by artm** [florish/byar#1]
Hi Floris

`byar` doesn't specify a license, which [prevents is to be used legally by third parties][1]. If it's an oversight, could you provide a license.

Thanks

[1]: https://choosealicense.com/no-permission/

**Comment by florish** [comment]
@artm Oh, yes, that's an oversight! At the time of publishing the gem, open source licenses weren't as important (as in: looked at by others and seen as necessary) as they are today.

I'll add the MIT license as a PR and will add you as collaborator on the project is that's OK. If you have feedback (as in: would like a different license), just comment on the PR. Otherwise, just hit "Merge"!
